name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup mdbook
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook
          version: 0.4.21

      - name: Setup mdbook-katex
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook-katex
          version: 0.2.10

      - uses: actions/checkout@v2

      - name: Build
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
